---
# tasks file for sample-apache
- name: ensure httpd is installed with all dependencies
  dnf:
    name:
      - httpd
      - mod_ssl
      - php
    state: present

- name: ensure httpd is enabled and started
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    - httpd
    - firewalld

      #- name: ensure firewalld is enable and started 
  
- name: open port 443 & 80 to accept incoming traffics
  firewalld:
    port: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp

- name: configure html file
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache
