---
# tasks file for sample-apache
- name: ensure httpd is installed
  dnf:
    name: httpd
    state: present

- name: ensure httpd is enabled and started
  systemd:
    name: httpd
    state: started
    enabled: yes

- name: ensure firewalld is installed
  dnf:
    name: firewalld
    state: present

- name: ensure firewalld is enable and started
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: open port 80 and 443 to accept incomming traffics
  firewalld:
    port: "{{item}}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 80/tcp
    - 443/tcp

- name: configure index.html file 
  template:
    src: templates/index.html.j2
    dest: /var/www/html/index.html
  notify: restart apache

