#!/bin/bash
ansible all -i /home/bob/ansible/inventory -m yum_repository -a "name=EPEL description=RHEL8 baseurl=https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rmp enabled=yes gpgcheck=no state=absent" 
