---
- hosts: database
  become: true
  tasks:
    - name: create file
      file:
        path: /mnt/mysql_backups/database_list.txt
        state: touch 

    - name: add content 
      lineinfile:
        path: /mnt/mysql_backups/database_list.txt
        line: dev,test,qa,prod
   
    - name: archive
      archive:
        path: /mnt/mysql_backups/database_list.txt
        dest: /mnt/mysql_backups/archive.gz
        format: gz
        force_archive: true

