---
- hosts: test
  become: true
  tasks:
    - name: create file with content  dev,test,qa,prod
      lineinfile:
        path: /mnt/mysql_backups/database_list.txt
        line: dev,test,qa,prod
        create: yes
    
    - name: cretate an archive file 
      archive:
        path: /mnt/mysql_backups/database_list.txt
        dest: /mnt/mysql_backups/archive.gz
        format: gz
        force_archive: true
 
