---
- hosts: database
  become: true
  tasks:
    - name: create a directory called facts.d
      file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: yes



    - name: create a file called custom.fact
      file:
        path: /etc/ansible/facts.d/custom.fact
        state: touch


    - name: create a file contents
      copy:
        content: |
          [sample_exam]
          server_role=mysql
        dest: /etc/ansible/facts.d/custom.fact


    - name: show debug messages
      debug:
        msg: "{{ansible_local.custom.sample_exam}}"



