---
- hosts: test
  become: true
  tasks:
    - name: create a partition
      parted:
        device: /dev/vdb
        number: 1
        flags: [ lvm ]
        state: present
 
    - name: create volume group
      lvg:
        vg: vg0
        pvs: /dev/vdb1
      when: ansible_devices.vdb is defined 

    - name: create logical volume group
      lvol:
        vg: vg0
        lv: lvol
        size: 900m
      when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g | float) > 1.5)

    - name: create logical volume group
      lvol:
        vg: vg0
        lv: lvol
        size: 900m
      when: ansible_lvm.vgs.vg0 is defined and ((ansible_lvm.vgs.vg0.size_g | float) < 1.5)
    - name: create filesystem
      filesystem:
        fstype: xfs
        dev: /dev/vg0/lvol
