---
- hosts: all
  become: true
  tasks:
   - name: install packages on all hosts
     dnf:
      name: 
        - mariadb
        - mod_ssl
        - httpd

      state: present

   - name: install development tools
     dnf:
      name:  '@Development tools'
      state: present
     when: ansible_hostname in groups['dev']
