---
- hosts: all
  become: true
  tasks:
    - name: ensure cronie is installed
      dnf:
        name: cronie
        state: present

    - name: ensure crond is is enable and started
      systemd:
        name: crond
        state: started
        enabled: yes

    - name: schedule job
      cron:
        name:  datejob
        minute: "0"
        hour: "12"
        user: root
        job: "date >> /root/datefile"

