---
- hosts: webservers
  become: true
  vars:
    selinux_state: enforcing
    selinux_policy: targeted
  roles:
    - /usr/share/ansible/roles/rhel-system-roles.selinux
  tasks:
    - name: set httpd_can_network_connect 
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

