---
- hosts: all
  become: true
  tasks:
    - name: set VM.swapness to 10 if server memory > 2048
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_memtotal_mb > 2048
          
 
    - name: show message server memory less than 2048
      debug:
        msg: system {{inventory_hostname}} {{ansible_memtotal_mb}} less than 2048MB
