---
- hosts: all
  become: true
  tasks:
    - name: set vm.swappiness to 10 if memory is > 2048
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_memtotal_mb > 2048

    - name: show debug message
      debug:
        msg: server {{ansible_hostname}} {{ansible_memtotal_mb}} less than 2048
