---
- hosts: all
  become: true
  tasks:
    - name: vm swappiness
      sysctl:
        name: vm.swappiness
        value: '10'
        state: present
      when: ansible_memfree_mb > 2048
     
    - name: debug output
      debug:
        msg: server {{ansible_hostname}} memory less than  2048
