---
- hosts: all
  become: true
  tasks:
    - name: change defalt target 
      file:
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link
