---
- hosts: all
  become: true
  tasks:
    - name: changes  default.target to multi-user.taget
      file:
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target
        state: link

