---
- hosts: all
  become: true
  tasks:
    - name: chnage default.target multiple.user.target
      file:
        src: /usr/lib/systemd/system/multi-user.target
        dest: /etc/systemd/system/default.target 

