---
- hosts: all
  become: true
  vars_files:
    - lock.yml
    - vars/user_list.yml
  tasks:
    - name: create devops group on dev host
      group:
        name: devops
        state: present
      when: ansible_hostname in groups['dev']

    - name: create users on dev host
      user:
        name: "{{item.username}}"
        password: "{{pw_dev | password_hash('sha512')}}"
        comment: "{{item.job}}"
      when: ansible_hostname in groups['dev'] and item.job == 'developer'
      with_items:
        "{{users}}"
        

    - name: append devops group
      user:
        name: "{{item.username}}"
        group: devops
        append: yes
      when: ansible_hostname in groups['dev'] and item.job == 'developer'
      with_items:
        "{{users}}"
    
    - name: create manager group on proxy host
      group:
        name: manager
        state: present
      when: ansible_hostname in groups['proxy']

    - name: create users on proxy host
      user:
        name: "{{item.username}}"
        password: "{{pw_mgr | password_hash('sha512')}}"
        comment: "{{item.job}}"
      when: ansible_hostname in groups['proxy'] and item.job == 'manager'
      with_items:
        "{{users}}"
        

    - name: append manager group
      user:
        name: "{{item.username}}"
        group: manager
        append: yes
      when: ansible_hostname in groups['proxy'] and item.job == 'manager'
      with_items:
        "{{users}}"
