---
# tasks file for sample-mysql
- name: create a new partition
  parted:
    device: /dev/sdb
    number: 
    flags: [ lvm ]
    state: absent
    part_end: 800MiB

- name: create a volumn group name vg_database
  lvg:
    vg: vg_database
    pvs: /dev/sdb1
    state: present

- name: create lvm name lv_mysql
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 512m
    state: present 

- name: create a filesystem 
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: create a directory name /mnt/mysql_backups
  file:
    path: /mnt/mysql_backup
    state: directory
    recurse: yes

- name: mount lv_mysql permanently on mysql80-community
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted

- name: install mysql-server packages with dependencies
  dnf:
    name:
      - mysql-server
      - python3-PyMySQL
    state: present

- name: start and enable mysqld services
  systemd:
    name: mysqld
    state: started
    enabled: yes 


- name: ensure firewalld is started and running
  systemd:
    name: firewalld
    state: started
    enabled: yes

- name: open 3306 to allow incomming  traffics
  firewalld:
    port: 3306/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: set root user password with all privilleges 
  mysql_user:
    name: root
    password: "{{database_password}}"
    priv: '*.*:ALL'
    state: present

- name: configure mysql server my.cnf file
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mysql
  
