---
# tasks file for sample-mysql
- name: create partion on /dev/sdb 1000M
  parted:
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
    part_end: 800MiB

- name: create volume group
  lvg:
    vg: vg_database
    pvs: /dev/sdb1
    state: present
  when: ansible_devices.sdb.partitions.sdb1 is defined

- name: create lvm
  lvol:
    vg: vg_database
    lv: lv_mysql
    size: 500m
    state: present

- name: create firlesystem
  filesystem:
    fstype: xfs
    dev: /dev/vg_database/lv_mysql

- name: create directory /mnt/mysql_backups
  file:
    path: /mnt/mysql_backups
    state: directory

- name: mount permenently on boot
  mount:
    path: /mnt/mysql_backups
    src: /dev/vg_database/lv_mysql
    fstype: xfs
    state: mounted

- name: install mysql and firewalld packages
  dnf:
    name:
      - mariadb-server
      - firewalld
      - python3-PyMySQL
    state: present

- name: mysql and firewalld are started and enabled
  systemd:
    name: "{{item}}"
    state: started
    enabled: yes
  loop:
    - mariadb
    - firewalld

- name: open port to allow incomming traffics
  firewalld:
    port: 3306/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: create privilleges for mysql rood user
  mysql_user:
    name: root
    password: "{{pw_dev}}"
    priv: '*.*:ALL'
    state: present

- name: configure mysql configs file my.cnf
  template:
    src: templates/my.cnf.j2
    dest: /etc/my.cnf
  notify: restart mysql
